### ISSUE TITLE
Can the app be built on emulator?

### ISSUE THREAD

**Issue by Eulerianial** [cardbookvr/skeleton#1]
Can we build things on emulator also?
I am facing issues in building over phone.

**Comment by Eulerianial** [comment]
Also, when I try to build on emulator Nexus_4_api_22, I get following error after apk is installed.

09-21 17:07:26.942 2720-2730/org.vijayriyaaz.riyaaz_vr E/System: java.lang.UnsatisfiedLinkError: No implementation found for void com.google.vrtoolkit.cardboard.CardboardViewNativeImpl.nativeDestroy(long) (tried Java_com_google_vrtoolkit_cardboard_CardboardViewNativeImpl_nativeDestroy and Java_com_google_vrtoolkit_cardboard_CardboardViewNativeImpl_nativeDestroy__J)
                                                                     at com.google.vrtoolkit.cardboard.CardboardViewNativeImpl.nativeDestroy(Native Method)
                                                                     at com.google.vrtoolkit.cardboard.CardboardViewNativeImpl.finalize(CardboardViewNativeImpl.java:137)
                                                                     at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:191)
                                                                     at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:174)
                                                                     at java.lang.Thread.run(Thread.java:818)

**Comment by Eulerianial** [comment]
The full crash log is the following:

09-21 17:07:20.925 2720-2720/org.vijayriyaaz.riyaaz_vr V/NFC: this device does not have NFC support
09-21 17:07:20.925 2720-2720/org.vijayriyaaz.riyaaz_vr W/NfcSensor: NFC is not supported on this phone or application doesn't have NFC permission.
09-21 17:07:21.146 2720-2720/org.vijayriyaaz.riyaaz_vr D/ConfigUtils: Parameters file not found for reading: java.io.FileNotFoundException: /storage/sdcard/Cardboard/current_device_params: open failed: ENOENT (No such file or directory)
09-21 17:07:21.146 2720-2720/org.vijayriyaaz.riyaaz_vr D/CardboardViewNativeImpl: NativeProxy not found
09-21 17:07:21.146 2720-2720/org.vijayriyaaz.riyaaz_vr D/CardboardViewNativeImpl: Loading native library vrtoolkit
09-21 17:07:21.147 2720-2720/org.vijayriyaaz.riyaaz_vr D/AndroidRuntime: Shutting down VM

```
                                                                     --------- beginning of crash
```

09-21 17:07:21.149 2720-2720/org.vijayriyaaz.riyaaz_vr E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: org.vijayriyaaz.riyaaz_vr, PID: 2720
                                                                         java.lang.RuntimeException: Unable to start activity ComponentInfo{org.vijayriyaaz.riyaaz_vr/org.vijayriyaaz.riyaaz_vr.MainActivity}: android.view.InflateException: Binary XML file line #8: Error inflating class com.google.vrtoolkit.cardboard.CardboardView
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
                                                                             at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:135)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:372)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                                          Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class com.google.vrtoolkit.cardboard.CardboardView
                                                                             at android.view.LayoutInflater.createView(LayoutInflater.java:633)
                                                                             at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
                                                                             at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
                                                                             at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:378)
                                                                             at android.app.Activity.setContentView(Activity.java:2145)
                                                                             at org.vijayriyaaz.riyaaz_vr.MainActivity.onCreate(MainActivity.java:49)
                                                                             at android.app.Activity.performCreate(Activity.java:5990)
                                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
                                                                             at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                             at android.os.Looper.loop(Looper.java:135) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
                                                                          Caused by: java.lang.reflect.InvocationTargetException
                                                                             at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                             at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                                                                             at android.view.LayoutInflater.createView(LayoutInflater.java:607)
                                                                             at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
                                                                             at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
                                                                             at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:378) 
                                                                             at android.app.Activity.setContentView(Activity.java:2145) 
                                                                             at org.vijayriyaaz.riyaaz_vr.MainActivity.onCreate(MainActivity.java:49) 
                                                                             at android.app.Activity.performCreate(Activity.java:5990) 
                                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278) 
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
                                                                             at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                             at android.os.Looper.loop(Looper.java:135) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
                                                                          Caused by: java.lang.UnsatisfiedLinkError: com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader[DexPathList[[dex file "/data/data/org.vijayriyaaz.riyaaz_vr/files/instant-run/dex/slice-support-annotations-22.1.0_2b8d5c3db1ddd784fd92ac8ba2a9cbdb622ec29d-classes.dex", dex file "/data/data/org.vijayriyaaz.riyaaz_vr/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/org.vijayriyaaz.riyaaz_vr/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/org.vijayriyaaz.riyaaz_vr/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/org.vijayriyaaz.riyaaz_vr/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/org.vijayriyaaz.riyaaz_vr/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/org.vijayriyaaz.riyaaz_vr/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/org.vijayriyaaz.riyaaz_vr/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/org.vijayriyaaz.riyaaz_vr/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/org.vijayriyaaz.riyaaz_vr/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/org.vijayriyaaz.riyaaz_vr/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/org.vijayriyaaz.riyaaz_vr/files/instant-run/dex/slice-internal_impl-22.1.0_03c1c6e87f7d552665539b2d0971c856280599f5-classes.dex", dex file "/data/data/org.vijayriyaaz.riyaaz_vr/files/instant-run/dex/slice-com.android.support-support-v4-22.1.0_5be8ef0537008bda1f475be39beac139dc06a645-classes.dex", dex file "/data/data/org.vijayriyaaz.riyaaz_vr/files/instant-run/dex/slice-com.android.support-appcompat-v7-22.1.0_8fc107fd7c3e76bab42978e34d007d75096881e6-classes.dex"],nativeLibraryDirectorie
09-21 17:07:26.941 2720-2730/org.vijayriyaaz.riyaaz_vr E/art: No implementation found for void com.google.vrtoolkit.cardboard.CardboardViewNativeImpl.nativeDestroy(long) (tried Java_com_google_vrtoolkit_cardboard_CardboardViewNativeImpl_nativeDestroy and Java_com_google_vrtoolkit_cardboard_CardboardViewNativeImpl_nativeDestroy__J)
09-21 17:07:26.942 2720-2730/org.vijayriyaaz.riyaaz_vr E/System: Uncaught exception thrown by finalizer
09-21 17:07:26.942 2720-2730/org.vijayriyaaz.riyaaz_vr E/System: java.lang.UnsatisfiedLinkError: No implementation found for void com.google.vrtoolkit.cardboard.CardboardViewNativeImpl.nativeDestroy(long) (tried Java_com_google_vrtoolkit_cardboard_CardboardViewNativeImpl_nativeDestroy and Java_com_google_vrtoolkit_cardboard_CardboardViewNativeImpl_nativeDestroy__J)
                                                                     at com.google.vrtoolkit.cardboard.CardboardViewNativeImpl.nativeDestroy(Native Method)
                                                                     at com.google.vrtoolkit.cardboard.CardboardViewNativeImpl.finalize(CardboardViewNativeImpl.java:137)
                                                                     at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:191)
                                                                     at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:174)
                                                                     at java.lang.Thread.run(Thread.java:818)
